import type { ConceptWorkspace } from '../types/conceptWorkspace';
const control = 'h-9 max-w-full rounded-md border border-[var(--border-primary)] bg-[var(--card-bg)] px-2.5 text-sm';
export function PhysicalWorkspaceControls({ workspace, disabled, onChange }: { workspace: ConceptWorkspace; disabled: boolean; onChange: (w: ConceptWorkspace) => void }) {
  return <fieldset disabled={disabled}><details className="text-sm"><summary className="cursor-pointer py-1 text-[var(--text-secondary)]">Key, tuning and exact frets</summary>
    <div className="space-y-3 pt-2">{workspace.entities.filter(e => e.kind === 'key').map(key => <label key={key.id} className="block">Context key <select className={control} value={key.root} onChange={event => onChange({ ...workspace, entities:workspace.entities.map(e => e.id === key.id ? { ...key, root:event.target.value } : e) })}>{['C','Db','D','Eb','E','F','F#','G','Ab','A','Bb','B'].map(root => <option key={root}>{root}</option>)}</select><span className="block text-sm">Reanalyzes the same chords; does not transpose them.</span></label>)}
      <label className="block">Physical tuning <select className={control} value={JSON.stringify(workspace.entities.find(e => e.kind === 'voicing')?.tuning)} onChange={event => onChange({ ...workspace, entities: workspace.entities.map(e => e.kind === 'voicing' ? { ...e, tuning:JSON.parse(event.target.value) } : e) })}><option value="[64,59,55,50,45,40]">Standard</option><option value="[64,59,55,50,45,38]">Drop D</option></select><span className="block text-sm">Keeps frets; retuning changes their sound.</span></label>
      {workspace.entities.filter(e => e.kind === 'voicing').map(v => <fieldset key={v.id}><legend>{v.label}</legend><div className="flex flex-wrap gap-2">{Array.from({ length:6 }, (_, i) => i+1).map(string => <label key={string}>String {string}<select aria-label={`${v.label} string ${string}`} className={`${control} block`} value={v.positions.find(p => p.string === string)?.fret ?? 'muted'} onChange={event => onChange({ ...workspace, entities:workspace.entities.map(e => e.id === v.id ? { ...v, positions:[...v.positions.filter(p => p.string !== string), ...(event.target.value === 'muted' ? [] : [{ string, fret:Number(event.target.value) }])].sort((a,b) => a.string - b.string) } : e) })}><option value="muted">Muted</option>{Array.from({ length:25 }, (_, i) => <option key={i} value={i}>{i === 0 ? 'Open' : i}</option>)}</select></label>)}</div></fieldset>)}
    </div>
  </details></fieldset>;
}
