import { expect, test } from '@playwright/test';

test('chord entry, CAGED selection, pinning and voicing comparison', async ({ page }) => {
  let modelCalls = 0;
  page.on('request', request => { if (request.url().endsWith('/tutor/turns')) modelCalls++; });
  await page.goto('/v2');
  await page.getByLabel('Explore a scale, key or chord').fill('Cmaj7');
  await page.getByRole('button', { name: 'Explore music', exact: true }).click();
  await expect(page.getByTestId('harmony-workspace')).toHaveAttribute('data-module', 'chord');
  await expect(page.getByLabel('Root', { exact: true })).toHaveValue('');
  await expect(page.getByLabel('Chord inspector')).toContainText('C major7');
  await expect(page.getByText('Function in key:')).toHaveCount(0);
  expect(modelCalls).toBe(0);
  await page.getByLabel('Root', { exact: true }).selectOption('C');
  await expect(page.getByTestId('harmony-workspace')).toHaveAttribute('data-module', 'scale');
  await page.getByRole('button', { name: 'Select C', exact: true }).click();
  await page.getByLabel('Voicing view').selectOption('caged');
  await expect(page.getByLabel('Voicing explorer').getByRole('button', { name: /^Select / })).toHaveCount(5);
  await page.getByLabel('Voicing explorer').getByRole('button', { name: /^Select / }).first().click();
  await expect(page.getByLabel('Voicing explorer')).toBeVisible();
  await page.getByRole('button', { name: /^Pin / }).first().click();
  await expect(page.getByLabel('Pinned voicings')).toBeVisible();
  await expect(page.getByTestId('scratch-count')).toHaveText('0 scratch chords');
  await page.getByRole('button', { name: 'Unpin', exact: true }).click();
  await expect(page.getByLabel('Pinned voicings')).toHaveCount(0);
  const peers = page.getByLabel('Voicing explorer').getByRole('button', { name: /^Compare / });
  await peers.nth(0).click(); await peers.nth(1).click();
  await expect(page.getByTestId('comparison-peer')).toHaveCount(2);
  await page.getByRole('button', { name: 'Clear comparison' }).click();
  await page.getByRole('button', { name: 'Compare current chord' }).click();
  await page.getByRole('button', { name: 'Back', exact: true }).click();
  await page.getByRole('button', { name: 'Select Dm', exact: true }).click();
  await page.getByRole('button', { name: 'Compare current chord' }).click();
  await expect(page.getByTestId('comparison-peer')).toHaveCount(2);
  await page.getByRole('button', { name: 'Clear comparison' }).click();
  await page.getByLabel('Ask the Tutor').fill('Offer a voicing candidate');
  await page.getByRole('button', { name: 'Ask', exact: true }).click();
  await page.getByRole('button', { name: 'Keep', exact: true }).click();
  await expect(page.getByLabel('Pinned voicings')).toBeVisible();
  await page.getByRole('button', { name: 'Unpin', exact: true }).click();
  await page.getByRole('button', { name: 'Dismiss', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Keep', exact: true })).toHaveCount(0);
  await page.screenshot({ path: 'test-results/chord-focus.png', fullPage: true });
});
