import { expect, test } from '@playwright/test';

test('Explore comparison coordinates music, inspection, views, audio and autosaved recovery', async ({ page }) => {
  const tutorRequests: string[] = [];
  page.on('request', request => { if (request.method() === 'POST' && request.url().includes('/tutor/')) tutorRequests.push(request.url()); });
  await page.goto('/v2');
  await page.getByRole('button', { name: 'Explore major vs minor' }).click();
  await expect(page.getByRole('heading', { name: 'G major vs G minor' })).toBeVisible();
  const sessionId = (await page.getByTestId('v2-active-session').innerText()).replace('Session ', '');
  const branchId = (await page.getByTestId('v2-active-branch').innerText()).replace('Branch ', '');
  const degrees = page.getByRole('region', { name: 'Degree strip' });
  const fretboard = page.getByRole('region', { name: 'Fretboard', exact: true });
  await degrees.getByRole('button', { name: 'G minor: Bb, degree b3, changed' }).click();
  await expect(fretboard.getByRole('button', { pressed: true }).first()).toHaveAccessibleName(/Bb/);
  await page.getByRole('button', { name: 'Back', exact: true }).click();
  await expect(fretboard.getByRole('button', { pressed: true })).toHaveCount(0);
  await page.getByLabel('Both roots').selectOption('D');
  await expect(page.getByRole('heading', { name: 'D major vs D minor' })).toBeVisible();
  await expect(page.getByRole('status').filter({ hasText: 'Draft autosaved' })).toBeVisible();
  await fretboard.getByLabel('Labels').selectOption('intervals');
  await expect(page.getByRole('status').filter({ hasText: 'Draft autosaved' })).toBeVisible();
  await page.getByRole('button', { name: 'Hear comparison' }).click();
  await expect(page.getByRole('button', { name: 'Stop playback' })).toBeVisible();
  await page.getByRole('button', { name: 'Stop playback' }).click();
  await page.getByRole('button', { name: 'Add View' }).click();
  await expect(page.getByLabel('View type')).toHaveText(/FretboardDegree strip/);
  await page.getByLabel('View type').selectOption('degree_strip');
  await page.getByRole('button', { name: 'Add selected view' }).click();
  await expect(page.getByRole('region', { name: 'Degree strip' })).toHaveCount(2);
  await page.getByRole('region', { name: 'Degree strip' }).last().getByRole('button', { name: 'Remove View' }).click();
  await expect(page.getByRole('region', { name: 'Degree strip' })).toHaveCount(1);
  await expect(page.getByRole('status').filter({ hasText: 'Draft autosaved' })).toBeVisible();
  const session = await page.request.get(`/api/v2/sessions/${sessionId}`).then(r => r.json());
  const draft = session.branches.find((b: {id: string}) => b.id === branchId).working_draft;
  expect(draft.entities.map((e: {root: string}) => e.root)).toEqual(['D', 'D']);
  expect(draft.blocks).toHaveLength(2);
  expect(draft.blocks[0].settings.labels).toBe('intervals');
  await page.screenshot({ path: 'test-results/workspace-desktop.png', fullPage: true });
  await page.reload();
  await page.locator(`[data-session-id="${sessionId}"]`).click();
  await page.getByRole('tab', { name: /G major vs G minor/ }).click();
  await expect(page.getByRole('heading', { name: 'D major vs D minor' })).toBeVisible();
  await expect(page.getByRole('region', { name: 'Fretboard', exact: true }).getByLabel('Labels')).toHaveValue('intervals');
  await page.setViewportSize({ width: 320, height: 800 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('button', { name: 'Hear comparison' }).focus();
  await page.keyboard.press('Enter');
  await expect(page.getByRole('button', { name: 'Stop playback' })).toBeFocused();
  await page.screenshot({ path: 'test-results/workspace-mobile.png', fullPage: true });
  expect(tutorRequests).toEqual([]);
});
