import { expect, test } from '@playwright/test'

test('scale entry is deterministic; palette, header, circle and Compare work', async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 1000 })
  const turns: string[] = []
  page.on('request', request => { if (request.url().endsWith('/tutor/turns')) turns.push(request.url()) })
  await page.goto('/v2')
  await page.getByLabel('Explore a scale or key').fill('A Dorian')
  await page.getByRole('button', { name: 'Explore scale', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Harmony', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Focus Am', exact: true })).toBeVisible()
  expect(turns).toHaveLength(0)
  await page.getByRole('button', { name: 'Add Am to scratch', exact: true }).click()
  await expect(page.getByTestId('scratch-count')).toHaveText('1 scratch chord')
  await page.getByRole('button', { name: 'Compare current scale' }).click()
  await page.getByLabel('Scale').selectOption('major')
  await page.getByRole('button', { name: 'Compare current scale' }).click()
  await expect(page.getByTestId('comparison-peer')).toHaveCount(2)
  await page.getByRole('button', { name: 'Clear comparison' }).click()
  await page.getByLabel('Ask the Tutor').fill('Show scale tools')
  await page.getByRole('button', { name: 'Ask', exact: true }).click()
  await page.getByRole('button', { name: 'Key D', exact: true }).click()
  await expect(page.getByLabel('Root')).toHaveValue('D')
  await page.getByRole('button', { name: 'Degree 3', exact: true }).click()
  await expect(page.getByRole('navigation', { name: 'Focus breadcrumb' })).toContainText('degree 3')
  await page.getByLabel('Tuning').selectOption('drop-d')
  await expect(page.getByRole('button', { name: 'Degree 3', exact: true })).toBeVisible()
  await page.screenshot({ path: 'test-results/harmony-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 320, height: 1000 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(320)
  await page.screenshot({ path: 'test-results/harmony-mobile.png', fullPage: true })
})
