import { expect, test } from '@playwright/test'

test('My Stuff opens fresh work and restores a saved linear revision', async ({ page }) => {
  await page.goto('/v2')
  const original = await page.request.post('/api/v2/progressions', { data: { title: 'Library progression', chords: [{ root: 'D', quality: 'major', voicing: [{ string: 1, fret: 10 }], tuning: 'standard' }], inspired_by: { title: 'Little Wing' } } }).then(r => r.json())
  await page.request.patch(`/api/v2/progressions/${original.id}/voicing`, { data: { expected_updated_at: original.updated_at, chord_index: 0, chord: { root: 'D', quality: 'major', voicing: [{ string: 1, fret: 14 }], tuning: 'standard' } } })
  await page.reload()
  const card = page.getByTestId('library-item').filter({ hasText: 'Library progression' })
  await expect(card).toContainText('Little Wing')
  await card.getByRole('button', { name: 'History' }).click()
  await card.getByRole('button', { name: 'Restore version 1', exact: true }).click()
  await expect(card.getByText('Version 3 · Current')).toBeVisible()
  const restored = await page.request.get(`/api/v2/progressions/${original.id}`).then(r => r.json())
  expect(restored.payload).toEqual(original.payload)
  await page.screenshot({ path: '/private/tmp/issue22-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: '/private/tmp/issue22-mobile.png', fullPage: true })
  await card.getByRole('button', { name: 'Open Library progression', exact: true }).click()
  await expect(page.getByTestId('progression-workspace')).toBeVisible()
  const first = await page.getByTestId('v2-active-session').textContent()
  await page.getByRole('button', { name: 'My Stuff', exact: true }).click()
  await page.getByRole('button', { name: 'Open Library progression', exact: true }).click()
  expect(await page.getByTestId('v2-active-session').textContent()).not.toEqual(first)
})
