import { expect, test } from '@playwright/test';

test('the chord sequence connects the fretboard, editor and Tutor without scrolling through forms', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto('/v2');
  await page.getByRole('button', { name: 'Build a four-chord progression' }).click();
  const sequence = page.getByRole('navigation', { name: 'Chords in this progression' });
  const editor = page.getByLabel('Progression editor', { exact: true });
  await sequence.getByRole('button', { name: 'Chord 3: A minor', exact: true }).click();
  await expect(editor.getByLabel('Chord root')).toHaveValue('A');
  await expect(editor.getByLabel('Step 3', { exact: true })).toBeVisible();
  await expect(editor.getByRole('listitem')).toHaveCount(1);
  await expect(page.getByLabel('Fretboard layers')).toContainText('A minor');
  await expect(page.getByLabel('Your Tutor')).toContainText('Four-chord progression · A minor');
  const fretboard = page.getByLabel('progression fretboard', { exact: true });
  await fretboard.scrollIntoViewIfNeeded();
  expect(await sequence.evaluate(el => el.getBoundingClientRect().top)).toBeGreaterThanOrEqual(0);
  expect(await sequence.evaluate(el => el.getBoundingClientRect().bottom)).toBeLessThan(1000);
  const fretboardTop = await fretboard.evaluate(el => el.getBoundingClientRect().top);
  await sequence.getByRole('button', { name: 'Chord 3: A minor', exact: true }).press('ArrowRight');
  await expect(editor.getByLabel('Chord root')).toHaveValue('F');
  await expect(page.getByLabel('Fretboard layers')).toContainText('F major');
  expect(Math.abs(await fretboard.evaluate(el => el.getBoundingClientRect().top) - fretboardTop)).toBeLessThan(2);
  await page.getByText('Neck range · frets 0–12', { exact: true }).click();
  await page.getByLabel('Neck region').selectOption('9-13');
  await page.getByRole('button', { name: 'Show these notes', exact: true }).click();
  await expect(fretboard.getByRole('button').first()).toBeVisible();
  await page.getByText(/^Neck range · frets/).click();
  await page.screenshot({ path: 'test-results/progression-connected-desktop.png', fullPage: true });
  await editor.getByLabel('Chord root').selectOption('D');
  await expect(sequence.getByRole('button', { name: 'Chord 4: D major', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await editor.getByText('Reorder or remove this chord', { exact: true }).click();
  await editor.getByRole('button', { name: 'Move earlier', exact: true }).click();
  await expect(editor.getByLabel('Step 3', { exact: true })).toBeVisible();
  await expect(sequence.getByRole('button', { name: 'Chord 3: D major', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await editor.getByRole('button', { name: 'Remove chord', exact: true }).click();
  await expect(sequence.getByRole('button', { name: /^Chord / })).toHaveCount(3);
  await expect(editor.getByLabel('Chord root')).toHaveValue('C');
  await page.setViewportSize({ width: 320, height: 900 });
  await page.getByRole('button', { name: 'Next →', exact: true }).click();
  await expect(page.getByLabel('Fretboard layers')).toContainText('G major');
  await page.getByRole('button', { name: 'Next →', exact: true }).click();
  await expect(page.getByLabel('Fretboard layers')).toContainText('A minor');
  const selectedBounds = await sequence.getByRole('button', { name: 'Chord 3: A minor', exact: true }).boundingBox();
  expect(selectedBounds!.x + selectedBounds!.width).toBeLessThanOrEqual(320);
  await page.screenshot({ path: 'test-results/progression-connected-mobile.png', fullPage: true });
  const overflowing = await page.evaluate(() => [...document.querySelectorAll('main *')].filter(el => el.getBoundingClientRect().right > innerWidth).map(el => ({ tag: el.tagName, class: el.className, right: el.getBoundingClientRect().right })).slice(0, 12));
  expect(await page.evaluate(() => document.documentElement.scrollWidth), JSON.stringify(overflowing)).toBeLessThanOrEqual(320);
});

test('analysis, playback and failed selections keep the connected music consistent', async ({ page }) => {
  await page.goto('/v2');
  await page.getByRole('button', { name: 'Build a four-chord progression' }).click();
  const sequence = page.getByRole('navigation', { name: 'Chords in this progression' });
  await page.getByRole('navigation', { name: 'Progression views' }).getByRole('button', { name: 'Harmonic function', exact: true }).click();
  await page.getByRole('button', { name: 'Explore function of chord 2: G major', exact: true }).click();
  await expect(sequence.getByRole('button', { name: 'Chord 2: G major', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(page.getByLabel('Fretboard layers')).toContainText('G major');
  await page.getByRole('navigation', { name: 'Progression views' }).getByRole('button', { name: 'Voice leading', exact: true }).click();
  await page.getByLabel('Voice leading', { exact: true }).getByRole('button', { name: 'C major → G major', exact: true }).click();
  await expect(page.getByLabel('Fretboard layers')).toContainText('C major');
  await expect(page.getByLabel('Fretboard layers')).toContainText('G major');
  await page.getByLabel('progression fretboard', { exact: true }).getByRole('button', { name: /G major, context$/ }).first().click();
  await expect(sequence.getByRole('button', { name: 'Chord 2: G major', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(page.getByLabel('Fretboard layers')).not.toContainText('C major');
  await page.getByRole('button', { name: 'Practice progression', exact: true }).click();
  await page.getByLabel('Count in', { exact: true }).selectOption('0');
  await page.getByLabel('Practice tempo').fill('240');
  await page.clock.install();
  await page.getByRole('button', { name: 'Start', exact: true }).click();
  await page.clock.runFor(1100);
  await expect(page.getByLabel('Fretboard layers')).toContainText('G major');
  await expect(sequence.getByRole('button', { name: 'Chord 2: G major', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: 'Pause', exact: true }).click();
  await page.clock.runFor(2000);
  await expect(page.getByLabel('Fretboard layers')).toContainText('G major');
  await sequence.getByRole('button', { name: 'Chord 4: F major', exact: true }).click();
  await expect(page.getByLabel('Practice controls')).toHaveCount(0);
  await expect(page.getByLabel('Progression editor').getByLabel('Chord root')).toHaveValue('F');
  await page.route('**/progression', route => route.request().method() === 'PATCH' ? route.fulfill({ status: 503, body: JSON.stringify({ detail: 'Try again' }) }) : route.continue());
  await sequence.getByRole('button', { name: 'Chord 1: C major', exact: true }).click();
  await expect(page.getByRole('alert')).toBeVisible();
  await expect(sequence.getByRole('button', { name: 'Chord 4: F major', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(page.getByLabel('Fretboard layers')).toContainText('F major');
});
