import { expect, test } from '@playwright/test';

test('original riff editing, uncommitted suggestions, intentional Save and exact reopen use the real owned API', async ({ page }) => {
  await page.goto('/v2');
  await page.getByRole('button', { name: 'Create riff', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Create riff' })).toBeVisible();
  const neck = page.getByRole('group', { name: 'Riff fretboard', exact: true });
  await neck.getByRole('button', { name: /string 5, fret 0,/ }).press('Enter');
  await neck.getByRole('button', { name: /string 5, fret 3,/ }).click();
  await page.getByRole('button', { name: /^Edit event 1:/ }).click();
  await neck.getByRole('button', { name: /string 4, fret 2,/ }).click();
  await page.getByLabel('Note length', { exact: true }).selectOption('2');
  await page.getByRole('button', { name: 'Done editing' }).click();
  await page.getByRole('button', { name: 'Add rest', exact: true }).click();
  await expect(page.getByTestId('riff-event-count')).toHaveText('3 events');
  await page.getByRole('button', { name: 'Hear Repeat the ending', exact: true }).click();
  await expect(page.getByText('Preview · not added', { exact: true })).toBeVisible();
  await expect(page.getByTestId('riff-event-count')).toHaveText('3 events');
  await page.getByRole('button', { name: 'Keep Repeat the ending', exact: true }).click();
  await expect(page.getByTestId('riff-event-count')).toHaveText('6 events');
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect(page.getByTestId('riff-event-count')).toHaveText('3 events');
  await page.getByRole('button', { name: 'Play riff', exact: true }).click();
  await expect(page.getByTestId('riff-play-along')).toBeVisible();
  await page.getByRole('button', { name: 'Stop', exact: true }).click();
  await page.getByLabel('Riff name').fill('My original riff');
  await page.getByLabel('Tempo', { exact: true }).fill('112');
  const createdResponse = page.waitForResponse(response => response.url().endsWith('/v2/riffs') && response.request().method() === 'POST');
  await page.getByRole('button', { name: 'Save riff', exact: true }).click();
  const created = await (await createdResponse).json();
  await expect(page.getByTestId('riff-save-state')).toHaveText('Saved');
  expect(created.payload.events.map((e: { beats: number }) => e.beats)).toEqual([2, .5, 2]);
  expect(created.payload.events.map((e: { position: unknown }) => e.position)).toEqual([{ string: 4, fret: 2 }, { string: 5, fret: 3 }, null]);
  await page.getByRole('complementary', { name: 'Main navigation' }).getByRole('button', { name: 'My Stuff', exact: true }).click();
  await page.getByLabel('Filter saved work').selectOption('riff');
  await page.getByRole('button', { name: 'Open My original riff', exact: true }).click();
  await expect(page.getByLabel('Riff name')).toHaveValue('My original riff');
  await expect(page.getByLabel('Tempo', { exact: true })).toHaveValue('112');
  await expect(page.getByTestId('riff-event-count')).toHaveText('3 events');
  await neck.getByRole('button', { name: /string 1, fret 0,/ }).click();
  const updateResponse = page.waitForResponse(response => response.url().endsWith(`/v2/riffs/${created.id}`) && response.request().method() === 'PUT');
  await page.getByRole('button', { name: 'Save riff', exact: true }).click();
  expect((await (await updateResponse).json()).id).toBe(created.id);
  await page.getByRole('complementary', { name: 'Main navigation' }).getByRole('button', { name: 'My Stuff', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Open My original riff', exact: true })).toHaveCount(1);
  await page.getByRole('button', { name: 'Open My original riff', exact: true }).click();
  await expect(page.getByTestId('riff-event-count')).toHaveText('4 events');
});

test('failed/stale Save and in-flight edits retain the draft; navigation only warns for changes', async ({ page }) => {
  await page.goto('/v2'); await page.getByRole('button', { name: 'Create riff', exact: true }).click();
  const neck = page.getByRole('group', { name: 'Riff fretboard', exact: true });
  await neck.getByRole('button', { name: /string 5, fret 0,/ }).click();
  await page.route('**/api/v2/riffs', route => route.fulfill({ status: 500, json: { detail: 'Save unavailable' } }));
  await page.getByRole('button', { name: 'Save riff', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Your changes are still here');
  await expect(page.getByTestId('riff-save-state')).toHaveText('Unsaved changes');
  await expect(page.getByTestId('riff-event-count')).toHaveText('1 event');
  await page.unroute('**/api/v2/riffs');
  let release: (() => void) | undefined, seen: (() => void) | undefined;
  const hold = new Promise<void>(resolve => { release = resolve; });
  const sent = new Promise<void>(resolve => { seen = resolve; });
  await page.route('**/api/v2/riffs', async route => { const response = await route.fetch(); seen?.(); await hold; await route.fulfill({ response }); });
  const response = page.waitForResponse(r => r.url().endsWith('/v2/riffs') && r.request().method() === 'POST');
  await page.getByRole('button', { name: 'Save riff', exact: true }).click(); await sent;
  await neck.getByRole('button', { name: /string 5, fret 3,/ }).click();
  release?.(); const created = await (await response).json();
  await expect(page.getByTestId('riff-event-count')).toHaveText('2 events');
  await expect(page.getByTestId('riff-save-state')).toHaveText('Unsaved changes');
  await page.unroute('**/api/v2/riffs');
  expect((await page.request.put(`/api/v2/riffs/${created.id}`, { data: { expected_updated_at: created.updated_at, payload: { ...created.payload, title: 'External saved version' } } })).ok()).toBe(true);
  await page.getByRole('button', { name: 'Save riff', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Your changes are still here');
  await expect(page.getByTestId('riff-event-count')).toHaveText('2 events');
  page.once('dialog', dialog => dialog.dismiss());
  await page.getByRole('complementary', { name: 'Main navigation' }).getByRole('button', { name: 'My Stuff', exact: true }).click();
  await expect(page.getByTestId('riff-editor')).toBeVisible();
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('complementary', { name: 'Main navigation' }).getByRole('button', { name: 'My Stuff', exact: true }).click();
  await page.getByRole('button', { name: 'Open External saved version', exact: true }).click();
  await expect(page.getByTestId('riff-event-count')).toHaveText('1 event');
  let dialogs = 0; page.on('dialog', async dialog => { dialogs++; await dialog.dismiss(); });
  await page.getByRole('button', { name: 'Hear Repeat the ending', exact: true }).click();
  await page.getByRole('complementary', { name: 'Main navigation' }).getByRole('button', { name: 'My Stuff', exact: true }).click();
  await expect(page.getByTestId('riff-editor')).toHaveCount(0); expect(dialogs).toBe(0);
});

test('alternate tuning, mobile containment, both themes, keyboard and reduced-motion playback stay useful', async ({ page }) => {
  const payload = { title: 'Alternate tuning riff', tempo: 180, tuning: [62, 57, 53, 48, 43, 38], tonal_center: null, events: [
    { id: 'low', beats: .5, position: { string: 6, fret: 0 } }, { id: 'rest', beats: 1, position: null }, { id: 'high', beats: 2, position: { string: 1, fret: 24 } },
  ] };
  const saved = await page.request.post('/api/v2/riffs', { data: payload }).then(r => r.json());
  await page.goto('/v2'); await page.getByRole('complementary', { name: 'Main navigation' }).getByRole('button', { name: 'My Stuff', exact: true }).click();
  await page.getByRole('button', { name: 'Open Alternate tuning riff', exact: true }).click();
  await expect(page.getByTestId('riff-editor')).toContainText('Original riff · D · A · F · C · G · D');
  await page.getByRole('button', { name: /^Edit event 3:/ }).press('Enter');
  await expect(page.getByLabel('Neck region')).toHaveValue('20');
  await page.getByRole('button', { name: 'Done editing' }).click();
  await page.getByRole('button', { name: 'Play riff', exact: true }).click();
  await expect(page.getByTestId('riff-play-along').locator('.play-along-string')).toHaveText(['D', 'A', 'F', 'C', 'G', 'D']);
  await page.getByRole('button', { name: 'Stop', exact: true }).click();
  await page.setViewportSize({ width: 1280, height: 900 });
  await page.getByRole('button', { name: /^Edit event 3:/ }).press('Enter');
  await expect(page.locator('.riff-timeline-event[aria-pressed=true] text')).toHaveCSS('fill', 'rgb(250, 251, 249)');
  await expect.poll(() => page.locator('.riff-timeline-board').evaluate(element => element.getBoundingClientRect().bottom)).toBeLessThanOrEqual(900);
  await page.screenshot({ path: '/tmp/riff-creator-desktop-light.png', fullPage: true });
  await page.getByRole('button', { name: 'Expand navigation', exact: true }).click();
  await page.getByRole('button', { name: 'Switch to dark mode', exact: true }).click();
  await page.getByRole('button', { name: 'Collapse navigation', exact: true }).click();
  await expect(page.locator('.riff-timeline-event[aria-pressed=true] text')).toHaveCSS('fill', 'rgb(20, 28, 24)');
  await page.screenshot({ path: '/tmp/riff-creator-desktop-dark.png', fullPage: true });
  await page.setViewportSize({ width: 320, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(320);
  await page.screenshot({ path: '/tmp/riff-creator-mobile-dark.png', fullPage: true });
  await page.getByRole('button', { name: 'Expand navigation', exact: true }).click();
  await page.getByRole('button', { name: 'Switch to light mode', exact: true }).click();
  await page.getByRole('button', { name: 'Collapse navigation', exact: true }).click();
  await page.screenshot({ path: '/tmp/riff-creator-mobile-light.png', fullPage: true });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.getByRole('button', { name: 'Play riff', exact: true }).press('Enter');
  await expect(page.getByTestId('riff-play-along')).toHaveAttribute('data-motion', 'stepped');
  await page.getByRole('button', { name: 'Stop', exact: true }).press('Enter');
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(320);
  expect((await page.request.get(`/api/v2/riffs/${saved.id}`).then(r => r.json())).payload).toEqual(payload);
});

test('audio-clock looping scrolls the cursor; source edits, hidden pages and navigation interrupt transport', async ({ page }) => {
  await page.goto('/v2'); await page.getByRole('button', { name: 'Create riff', exact: true }).click();
  const neck = page.getByRole('group', { name: 'Riff fretboard', exact: true });
  await neck.getByRole('button', { name: /string 5, fret 0,/ }).click();
  await neck.getByRole('button', { name: /string 5, fret 3,/ }).click();
  await page.getByLabel('Tempo', { exact: true }).fill('180');
  await page.getByRole('button', { name: 'Play riff', exact: true }).click();
  const board = page.getByTestId('riff-play-along');
  await expect.poll(async () => Number(await board.getAttribute('data-offset'))).toBeGreaterThan(.6);
  await expect.poll(async () => Number(await board.getAttribute('data-offset'))).toBeLessThan(.5);
  await neck.getByRole('button', { name: /string 4, fret 2,/ }).click();
  await expect(board).toHaveCount(0); await expect(page.getByTestId('riff-event-count')).toHaveText('3 events');
  await page.getByRole('button', { name: 'Hear Repeat the ending', exact: true }).click();
  await expect(board).toBeVisible();
  await page.getByLabel('Note length', { exact: true }).selectOption('1');
  await expect(board).toHaveCount(0); await expect(page.getByText('Preview · not added', { exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: 'Play riff', exact: true }).click();
  await expect(board).toBeVisible();
  await page.evaluate(() => { Object.defineProperty(document, 'hidden', { configurable: true, value: true }); document.dispatchEvent(new Event('visibilitychange')); });
  await expect(board).toHaveCount(0);
  await page.evaluate(() => { Object.defineProperty(document, 'hidden', { configurable: true, value: false }); document.dispatchEvent(new Event('visibilitychange')); });
  await page.getByRole('button', { name: 'Play riff', exact: true }).click(); await expect(board).toBeVisible();
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('complementary', { name: 'Main navigation' }).getByRole('button', { name: 'Explore', exact: true }).click();
  await expect(board).toHaveCount(0); await expect(page.getByTestId('riff-editor')).toHaveCount(0);
});
