import { expect, test } from '@playwright/test'

test('SongStudy opens independently of Harmony and returns to the same workspace', async ({ page }) => {
  await page.goto('/v2')
  await page.getByRole('button', { name: 'What makes A Dorian different?' }).click()
  await expect(page.getByRole('heading', { name: 'Harmony', exact: true })).toBeVisible()
  const before = await page.getByTestId('v2-active-branch').textContent()
  await page.getByRole('button', { name: 'Study a song', exact: true }).click()
  await expect(page.getByTestId('song-study-search')).toBeVisible()
  await page.getByRole('button', { name: 'Back to workspace', exact: true }).click()
  await expect(page.getByLabel('Scale', { exact: true })).toHaveValue('dorian')
  await expect(page.getByTestId('v2-active-branch')).toHaveText(before!)
})

test('song tab, learning map, enrichment, copied exercise and library survive reopen', async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 1000 })
  await page.goto('/v2')
  await page.getByRole('button', { name: 'Study a song', exact: true }).click()
  await page.getByLabel('Search songs').fill('fixture')
  await page.getByRole('button', { name: 'Search', exact: true }).click()
  await page.getByRole('button', { name: 'Drop D guitar', exact: true }).click()
  await expect(page.getByTestId('song-study-title')).toContainText('Study Fixture')
  await page.getByLabel('Playback source').selectOption('practice')
  await expect(page.getByRole('heading', { name: 'Measures 1–4', exact: true })).toBeVisible()
  await expect(page.getByTestId('fretboard-active-note').filter({ hasText: 'D' }).first()).toBeVisible()
  await page.getByRole('button', { name: 'Save to My Stuff', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Saved to My Stuff', exact: true })).toBeVisible()
  await page.getByText('Learning map · selection M1–1', { exact: true }).click()
  await page.getByLabel('Range name').fill('Opening drill')
  await page.getByRole('button', { name: 'Save selected range', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Saved range: Opening drill · M1–1', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Enhance for learning', exact: true }).click()
  await expect(page.getByTestId('song-study-enrichment-range')).toContainText('Opening phrase')
  await page.getByRole('button', { name: 'Create exercise', exact: true }).click()
  await page.getByLabel('Exercise title').fill('Song rhythm drill')
  await page.getByLabel('Practice goal').fill('Keep the rest in time')
  await page.getByLabel('Step order').fill('1,2,1')
  await page.getByRole('button', { name: 'Save exercise', exact: true }).click()
  await expect(page.getByText('Exercise saved.', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Close', exact: true }).click()
  await page.getByRole('button', { name: 'Show full tab', exact: true }).click()
  await expect(page.getByTestId('song-study-full-tab')).toBeVisible()
  await page.getByRole('button', { name: 'Show overview + focus', exact: true }).click()
  await page.getByLabel('Playback source').selectOption('practice')
  await page.getByRole('button', { name: 'Practice selection', exact: true }).click()
  await page.getByLabel('Count in').selectOption('0')
  await page.getByLabel('Practice audio').selectOption('guide')
  await page.getByRole('button', { name: 'Start', exact: true }).click()
  await expect(page.getByTestId('practice-status')).toHaveText('Playing')
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  await expect(page.getByTestId('practice-status')).toHaveText('Paused')
  await page.getByRole('button', { name: 'Exit Practice', exact: true }).click()
  await page.screenshot({ path: 'test-results/song-study-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 320, height: 900 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(320)
  await page.screenshot({ path: 'test-results/song-study-mobile.png', fullPage: true })
  await page.reload()
  await page.getByRole('button', { name: 'Open Practice Band - Study Fixture', exact: true }).click()
  await expect(page.getByTestId('song-study-title')).toContainText('Study Fixture')
  await page.getByLabel('Playback source').selectOption('practice')
  await page.getByText('Learning map · selection M1–1', { exact: true }).click()
  await expect(page.getByRole('button', { name: 'Saved range: Opening drill · M1–1', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Remove enhancement', exact: true }).click()
  await expect(page.getByTestId('song-study-enrichment-range')).toHaveCount(0)
  await page.getByRole('button', { name: 'Explore', exact: true }).click()
  await page.getByRole('button', { name: 'Open Song rhythm drill', exact: true }).click()
  await expect(page.getByTestId('exercise-workspace')).toContainText('Song rhythm drill')
  await page.getByRole('button', { name: 'Practice exercise', exact: true }).click()
  await expect(page.getByLabel('Practice audio')).toBeVisible()
  const exercises = await (await page.request.get('/api/v2/exercises')).json()
  const exercise = exercises.find((item: { title: string }) => item.title === 'Song rhythm drill')
  expect(exercise.payload.steps.map((step: { beats: number }) => step.beats)).toEqual([1, 0.5, 1])
  expect(exercise.payload.steps[0].tuning).toEqual([64, 59, 55, 50, 45, 38])
  expect(exercise.payload.steps[1].positions).toEqual([])
})

test('song search reports provider errors and empty results, then recovers', async ({ page }) => {
  await page.goto('/v2')
  await page.getByRole('button', { name: 'Study a song', exact: true }).click()
  await page.getByLabel('Search songs').fill('provider error')
  await page.getByRole('button', { name: 'Search', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Song provider unavailable')
  await page.getByLabel('Search songs').fill('missing')
  await page.getByRole('button', { name: 'Search', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('No songs found')
  await page.getByLabel('Search songs').fill('fixture')
  await page.getByRole('button', { name: 'Search', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Drop D guitar', exact: true })).toBeVisible()
})

test('practice timing follows rests, fractional beats, count-in and loop boundaries', async () => {
  const { beatDuration, practicePosition } = await import('../src/v2/practiceTiming')
  expect(beatDuration({ duration: [1, 8], notes: [] })).toBe(0.5)
  expect(beatDuration({ notes: [] })).toBeNull()
  expect(practicePosition([1, 0.5, 1], 3, 4, true)).toMatchObject({ index: -1, count: 1 })
  expect(practicePosition([1, 0.5, 1], 5, 4, true)).toMatchObject({ index: 1, next: 2 })
  expect(practicePosition([1, 0.5, 1], 6.5, 4, true)).toMatchObject({ index: 0, finished: false })
  expect(practicePosition([1, 0.5, 1], 6.5, 4, false)).toMatchObject({ index: 2, finished: true })
})
