import { expect, test } from '@playwright/test';

test('Preview replays focus, Return preserves the present, Restore appends history without changing saved work', async ({ page }) => {
  await page.goto('/v2');
  await page.getByRole('button', { name: 'Explore major vs minor' }).click();
  await expect(page.getByText('Draft autosaved', { exact: true })).toBeVisible();
  const sid = (await page.getByTestId('v2-active-session').innerText()).replace('Session ', '');
  const bid = (await page.getByTestId('v2-active-branch').innerText()).replace('Branch ', '');
  const branch = () => page.request.get(`/api/v2/sessions/${sid}`).then(r => r.json()).then(s => s.branches.find((b: {id: string}) => b.id === bid));
  if (!(await page.getByRole('dialog', {name:'Tutor',exact:true}).isVisible())) await page.getByRole('button', {name:'Open Tutor',exact:true}).click();
  await page.getByTestId('tutor-chat-input').fill('Change the first scale to G Dorian');
  await page.getByTestId('tutor-chat-send').click();
  await expect(page.getByText('Tutor change applied', { exact: true })).toBeVisible();
  const snapshot = (await branch()).working_draft;
  await page.getByRole('button', { name: 'Save as study', exact: true }).click();
  await expect(page.getByText('Study saved in My Stuff.', { exact: true })).toBeVisible();
  const savedBranch = await branch();
  const aid = savedBranch.current_artifact_id;
  const savedArtifact = await page.request.get(`/api/v2/concept-studies/${aid}`).then(r => r.json());
  await page.getByLabel('Both roots', { exact: true }).selectOption('D');
  await expect(page.getByText('Draft autosaved', { exact: true })).toBeVisible();
  const current = (await branch()).working_draft;
  if (!(await page.getByRole('dialog', {name:'Tutor',exact:true}).isVisible())) await page.getByRole('button', {name:'Open Tutor',exact:true}).click();
  await page.getByTestId('tutor-chat-input').fill('My unsent question');
  if (!(await page.getByRole('dialog', {name:'Tutor',exact:true}).isVisible())) await page.getByRole('button', {name:'Open Tutor',exact:true}).click();
  await page.getByRole('button', { name: 'Preview turn workspace', exact: true }).click();
  await expect(page.getByRole('region', { name: 'Turn snapshot preview' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'G dorian vs G minor' })).toBeFocused();
  await expect(page.getByRole('region', { name: 'Turn snapshot preview' }).getByText('Tutor focus: G target', { exact: true })).toBeVisible();
  await expect(page.getByRole('region', { name: 'Turn snapshot preview' }).locator('[data-tutor-focus=true]').first()).toBeVisible();
  await expect(page.getByLabel('Both roots', { exact: true })).not.toBeVisible();
  expect((await branch()).working_draft).toEqual(current);
  await page.screenshot({ path: '/private/tmp/issue63-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 320, height: 800 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: '/private/tmp/issue63-mobile.png', fullPage: true });
  await page.getByRole('button', { name: 'Return to current', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'D dorian vs D minor' })).toBeFocused();
  expect((await branch()).working_draft).toEqual(current);
  await expect(page.getByTestId('tutor-chat-input')).toHaveValue('My unsent question');
  if (!(await page.getByRole('dialog', {name:'Tutor',exact:true}).isVisible())) await page.getByRole('button', {name:'Open Tutor',exact:true}).click();
  await page.getByRole('button', { name: 'Preview turn workspace', exact: true }).click();
  await page.getByRole('button', { name: 'Restore this state', exact: true }).click();
  await page.getByRole('button', {name:'Open Tutor',exact:true}).click();
  await expect(page.getByText('Earlier state restored', { exact: true })).toBeVisible();
  await expect(page.getByTestId('tutor-chat-input')).toHaveValue('My unsent question');
  expect((await branch()).working_draft).toEqual({ ...snapshot, version: current.version + 1 });
  expect(await page.request.get(`/api/v2/concept-studies/${aid}`).then(r => r.json())).toEqual(savedArtifact);
  await expect(page.getByRole('button', { name: 'Undo Tutor change', exact: true })).toHaveCount(0);
  if (!(await page.getByRole('dialog', {name:'Tutor',exact:true}).isVisible())) await page.getByRole('button', {name:'Open Tutor',exact:true}).click();
  await expect(page.getByRole('button', { name: 'Preview turn workspace', exact: true })).toHaveCount(2);
  await page.reload();
  await page.locator(`[data-session-id="${sid}"]`).click();
  await page.getByLabel('Current workspace', { exact: true }).selectOption(bid);
  await page.getByRole('button', {name:'Open Tutor',exact:true}).click();
  await expect(page.getByText('Earlier state restored', { exact: true })).toBeVisible();
  if (!(await page.getByRole('dialog', {name:'Tutor',exact:true}).isVisible())) await page.getByRole('button', {name:'Open Tutor',exact:true}).click();
  await expect(page.getByTestId('tutor-chat-message-assistant').first()).toContainText('G Dorian');
});

test('Stale restore stays in preview and leaves the current server draft intact', async ({ page }) => {
  await page.goto('/v2');
  await page.getByRole('button', { name: 'Explore major vs minor' }).click();
  await expect(page.getByText('Draft autosaved', { exact: true })).toBeVisible();
  if (!(await page.getByRole('dialog', {name:'Tutor',exact:true}).isVisible())) await page.getByRole('button', {name:'Open Tutor',exact:true}).click();
  await page.getByTestId('tutor-chat-input').fill('Change to Dorian');
  await page.getByTestId('tutor-chat-send').click();
  await expect(page.getByText('Tutor change applied', { exact: true })).toBeVisible();
  const sid = (await page.getByTestId('v2-active-session').innerText()).replace('Session ', '');
  const bid = (await page.getByTestId('v2-active-branch').innerText()).replace('Branch ', '');
  const b = await page.request.get(`/api/v2/sessions/${sid}`).then(r => r.json()).then(s => s.branches.find((b: {id: string}) => b.id === bid));
  if (!(await page.getByRole('dialog', {name:'Tutor',exact:true}).isVisible())) await page.getByRole('button', {name:'Open Tutor',exact:true}).click();
  await page.getByRole('button', { name: 'Preview turn workspace' }).click();
  b.working_draft.entities[0].root = 'Eb';
  const updated = await page.request.put(`/api/v2/sessions/${sid}/branches/${bid}/workspace`, { data: { expected_version: b.working_draft.version, workspace: b.working_draft } }).then(r => r.json());
  await page.getByRole('button', { name: 'Restore this state' }).click();
  await expect(page.getByRole('alert')).toContainText('current draft changed');
  await expect(page.getByRole('region', { name: 'Turn snapshot preview' })).toBeVisible();
  expect(await page.request.get(`/api/v2/sessions/${sid}`).then(r => r.json()).then(s => s.branches.find((b: {id: string}) => b.id === bid).working_draft)).toEqual(updated.working_draft);
  await page.getByRole('button', { name: 'Return to current' }).click();
  await expect(page.getByRole('heading', { name: 'G dorian vs G minor' })).toBeVisible();
});
