import { expect, test } from '@playwright/test';

test('workspace Tutor is a dismissible panel and failures preserve editable music', async ({page}) => {
  await page.goto('/v2');
  await page.getByRole('button',{name:'Explore major vs minor',exact:true}).click();
  await expect(page.getByText('Draft autosaved',{exact:true})).toBeVisible();
  await page.setViewportSize({width:320,height:800});
  await page.getByRole('button',{name:'Open Tutor',exact:true}).click();
  const panel=page.getByRole('complementary',{name:'Tutor',exact:true});
  await expect(panel).toBeVisible();
  await page.screenshot({path:'/private/tmp/issue68-mobile-tutor.png',fullPage:true});
  await page.keyboard.press('Escape');
  await expect(panel).not.toBeVisible();
  await expect(page.getByRole('button',{name:'Open Tutor',exact:true})).toBeFocused();
  await page.route('**/concept-workspaces/resolve', route=>route.fulfill({status:503}));
  await page.getByLabel('Both roots',{exact:true}).selectOption('A');
  await expect(page.getByRole('alert')).toContainText('previous draft is unchanged');
  await expect(page.getByLabel('Both roots',{exact:true})).toHaveValue('G');
  await page.unroute('**/concept-workspaces/resolve');
  await page.getByLabel('Both roots',{exact:true}).selectOption('A');
  await expect(page.getByText('Draft autosaved',{exact:true})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.evaluate(() => {
    const create = AudioContext.prototype.createBufferSource;
    AudioContext.prototype.createBufferSource = function() { AudioContext.prototype.createBufferSource=create; throw new Error('Audio unavailable'); };
  });
  await page.getByRole('button',{name:'Hear comparison',exact:true}).click();
  await expect(page.getByRole('alert')).toContainText('Audio could not start');
  await expect(page.getByLabel('Both roots',{exact:true})).toHaveValue('A');
  await page.getByRole('button',{name:'Hear comparison',exact:true}).click();
  await page.getByRole('button',{name:'Stop playback',exact:true}).click();
  await expect(page.getByRole('alert')).not.toBeVisible();
  await page.screenshot({path:'/private/tmp/issue68-mobile.png',fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.getByRole('button',{name:'Open Tutor',exact:true}).click();
  await expect(panel).toBeVisible();
  await page.screenshot({path:'/private/tmp/issue68-desktop.png',fullPage:true});
  await panel.getByRole('button',{name:'Close Tutor',exact:true}).click();
  const old = await page.request.post('/api/v2/sessions').then(r=>r.json());
  await page.request.patch(`/api/v2/sessions/${old.id}/branches/${old.branches[0].id}`,{data:{title:'Older study',current_artifact_kind:'concept_study',current_artifact_id:'old-study'}});
  await page.goto('/v2');
  await page.locator(`[data-session-id="${old.id}"]`).click();
  await expect(page.getByRole('alert')).toContainText('older study is unsupported');
  await page.getByRole('button',{name:'Open Explore',exact:true}).click();
  await expect(page.getByRole('heading',{name:'What would you like to explore?'})).toBeVisible();
});
