import { expect, test } from '@playwright/test';

test('Music bar selects independent views, steps back from inspection and clears on music edits', async ({ page }) => {
  await page.goto('/v2');
  await page.getByRole('button', { name: 'Explore major vs minor' }).click();
  await expect(page.getByText('Draft autosaved', { exact: true })).toBeVisible();
  const boards = page.getByRole('region', { name: 'Fretboard', exact: true });
  const context = page.getByRole('region', { name: 'Music context', exact: true });
  await boards.first().getByRole('button', { name: 'Select Fretboard', exact: true }).click();
  await context.getByLabel('Frets', { exact: true }).selectOption('0-5');
  await expect(page.getByText('Draft autosaved', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Add View', exact: true }).click();
  await page.getByLabel('View type').selectOption('fretboard');
  await page.getByLabel('Musical source').selectOption({ label: 'G major' });
  await page.getByRole('button', { name: 'Add selected view' }).click();
  await expect(boards).toHaveCount(2);
  await boards.last().getByRole('button', { name: 'Select Fretboard', exact: true }).click();
  await context.getByLabel('Frets', { exact: true }).selectOption('7-12');
  await expect(boards.first().getByRole('group', { name: /Fretboard, frets 0 to 5/ })).toBeVisible();
  await expect(boards.last().getByRole('group', { name: /Fretboard, frets 7 to 12/ })).toBeVisible();
  await boards.last().getByRole('button', { name: /G major: B,/ }).first().click();
  await expect(context).toContainText('Inspecting B');
  await expect(context.getByLabel('Frets', { exact: true })).toHaveCount(0);
  await context.getByRole('button', { name: 'Back', exact: true }).click();
  await expect(context.getByLabel('Frets', { exact: true })).toHaveValue('7-12');
  await page.setViewportSize({ width: 320, height: 800 });
  await expect(context).toHaveCSS('position', 'fixed');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: '/private/tmp/issue95-mobile.png', fullPage: true });
  await context.getByRole('button', { name: 'Back', exact: true }).click();
  await page.getByLabel('Both roots').selectOption('D');
  await expect(context).toHaveCount(0);
  await expect(boards.last().getByRole('button', { name: 'Select Fretboard', exact: true })).toHaveAttribute('aria-current', 'false');
});

test('Source chips add, reorder and remove through update_view; empty view drafts stay local', async ({ page }) => {
  await page.goto('/v2');
  await page.getByRole('button', { name: 'Explore major vs minor' }).click();
  await expect(page.getByText('Draft autosaved', { exact: true })).toBeVisible();
  const sid = (await page.getByTestId('v2-active-session').innerText()).replace('Session ', '');
  const bid = (await page.getByTestId('v2-active-branch').innerText()).replace('Branch ', '');
  const draft = () => page.request.get(`/api/v2/sessions/${sid}`).then(r => r.json()).then(s => s.branches.find((b: {id:string}) => b.id === bid).working_draft);
  const before = await draft();
  await page.getByRole('button', { name: 'Add View', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Add selected view' })).toBeDisabled();
  expect(await draft()).toEqual(before);
  await page.getByLabel('View type').selectOption('fretboard');
  await page.getByLabel('Musical source').selectOption({ label: 'G major' });
  await page.getByRole('button', { name: 'Add selected view' }).click();
  const context = page.getByRole('region', { name: 'Music context', exact: true });
  await context.getByLabel('Add source', { exact: false }).selectOption({ label: 'G minor' });
  const updated = page.waitForRequest(request => request.url().endsWith('/concept-workspaces/update-view'));
  await context.getByRole('button', { name: 'Add source to view' }).click();
  expect((await updated).postDataJSON().view.op).toBe('update_view');
  await expect(context.getByRole('listitem')).toHaveCount(2);
  await context.getByRole('button', { name: 'Move G minor earlier' }).click();
  await expect(context.getByRole('listitem').first()).toContainText('G minor');
  await expect(page.getByText('Draft autosaved', { exact: true })).toBeVisible();
  const reordered = await draft();
  expect(reordered.blocks.at(-1).sources).toEqual(before.entities.map((e: {id:string}) => e.id).reverse());
  await context.getByRole('button', { name: 'Remove source G major' }).click();
  await expect(context.getByRole('listitem')).toHaveCount(1);
  await expect(context.getByRole('button', { name: 'Remove source G minor' })).toBeDisabled();
  await page.screenshot({ path: '/private/tmp/issue95-desktop.png', fullPage: true });
  await page.getByLabel('Both roots').selectOption('D');
  await expect(context).toHaveCount(0);
});

test('Derived chords and steps require an explicit parent binding or materialization for Add View', async ({ page }) => {
  await page.goto('/v2');
  await page.getByRole('button', { name: 'Explore I–V–vi–IV', exact: true }).click();
  await expect(page.getByText('Draft autosaved', { exact: true })).toBeVisible();
  const sid = (await page.getByTestId('v2-active-session').innerText()).replace('Session ', '');
  const bid = (await page.getByTestId('v2-active-branch').innerText()).replace('Branch ', '');
  const draft = () => page.request.get(`/api/v2/sessions/${sid}`).then(r => r.json()).then(s => s.branches.find((b: {id:string}) => b.id === bid).working_draft);
  const before = await draft();
  await page.getByRole('button', { name: /Select chord 2:/ }).click();
  await page.getByRole('button', { name: 'Add View', exact: true }).click();
  await page.getByLabel('View type').selectOption('key_family');
  await expect(page.getByRole('button', { name: 'Add selected view' })).toBeDisabled();
  await page.getByRole('button', { name: 'Bind parent key' }).click();
  await page.getByRole('button', { name: 'Add selected view' }).click();
  await expect(page.getByText('Draft autosaved', { exact: true })).toBeVisible();
  expect((await draft()).entities).toEqual(before.entities);
  const family = page.getByRole('region', { name: 'Key family', exact: true });
  await family.getByRole('button', { name: /Inspect ii / }).click();
  await page.getByRole('button', { name: 'Add View', exact: true }).click();
  await page.getByLabel('View type').selectOption('fretboard');
  await expect(page.getByRole('button', { name: 'Bind parent key' })).toBeEnabled();
  await page.getByRole('button', { name: 'Materialize first' }).click();
  await expect(page.getByRole('button', { name: 'Add selected view' })).toBeEnabled();
  await page.getByRole('button', { name: 'Add selected view' }).click();
  await expect(page.getByText('Draft autosaved', { exact: true })).toBeVisible();
  const after = await draft();
  const chord = after.entities.find((e: {kind:string}) => e.kind === 'chord');
  expect(chord).toBeTruthy();
  expect(after.blocks.at(-1).sources).toEqual([chord.id]);
  expect(after.entities).toHaveLength(before.entities.length + 1);
});
