import { expect, test } from '@playwright/test';

test('Save named work, save a version, reload and reopen exact musical state', async ({ page }) => {
  await page.goto('/v2');
  await page.getByRole('button', { name: 'Explore major vs minor' }).click();
  await expect(page.getByText('Draft autosaved', { exact: true })).toBeVisible();
  const sid = (await page.getByTestId('v2-active-session').innerText()).replace('Session ', '');
  const bid = (await page.getByTestId('v2-active-branch').innerText()).replace('Branch ', '');
  const branch = () => page.request.get(`/api/v2/sessions/${sid}`).then(r => r.json()).then(s => s.branches.find((b: {id: string}) => b.id === bid));
  await page.getByLabel('Both roots', { exact: true }).selectOption('Bb');
  await expect(page.getByText('Draft autosaved', { exact: true })).toBeVisible();
  await page.getByRole('region', { name: 'Fretboard', exact: true }).getByRole('button', { name: 'Select Fretboard', exact: true }).click();
  await page.getByRole('region', { name: 'Music context', exact: true }).getByLabel('Labels').selectOption('intervals');
  await expect(page.getByText('Draft autosaved', { exact: true })).toBeVisible();
  await page.getByLabel('Study name', { exact: true }).fill('Warm scale comparison');
  await page.getByRole('button', { name: 'Save as study', exact: true }).click();
  await expect(page.getByText('Study saved in My Stuff.', { exact: true })).toBeVisible();
  const first = await branch();
  const aid = first.current_artifact_id;
  expect((await page.request.get(`/api/v2/library/${aid}/revisions`).then(r => r.json())).length).toBe(1);
  await page.getByLabel('Both roots', { exact: true }).selectOption('D');
  await expect(page.getByText('Draft autosaved', { exact: true })).toBeVisible();
  expect((await page.request.get(`/api/v2/library/${aid}/revisions`).then(r => r.json())).length).toBe(1);
  const versionSaved = page.waitForResponse(r => r.url().endsWith('/workspace/save'));
  await page.getByRole('button', { name: 'Save version', exact: true }).click();
  expect((await versionSaved).ok()).toBe(true);
  expect((await page.request.get(`/api/v2/library/${aid}/revisions`).then(r => r.json())).length).toBe(2);
  const exact = (await branch()).working_draft;
  await page.reload();
  await page.locator(`[data-session-id="${sid}"]`).click();
  await page.getByRole('tab', { name: /Warm scale comparison/ }).click();
  await expect(page.getByRole('heading', { name: 'D major vs D minor' })).toBeVisible();
  expect((await branch()).working_draft).toEqual(exact);
  await page.getByRole('button', { name: 'My Stuff', exact: true }).click();
  await page.getByRole('button', { name: 'Open Warm scale comparison', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'D major vs D minor' })).toBeVisible();
  await page.getByRole('region', { name: 'Fretboard', exact: true }).getByRole('button', { name: 'Select Fretboard', exact: true }).click();
  await expect(page.getByRole('region', { name: 'Music context', exact: true }).getByLabel('Labels')).toHaveValue('intervals');
  expect((await page.getByTestId('v2-active-session').innerText())).not.toContain(sid);
  await page.screenshot({ path: '/private/tmp/issue61-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 320, height: 800 });
  await page.getByLabel('Study name', { exact: true }).focus();
  await expect(page.getByLabel('Study name', { exact: true })).toBeFocused();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: '/private/tmp/issue61-mobile.png', fullPage: true });
});

test('A stale saved-study conflict retains the draft and recovers as independent named work', async ({ page }) => {
  await page.goto('/v2');
  await page.getByRole('button', { name: 'Explore major vs minor' }).click();
  await expect(page.getByText('Draft autosaved', { exact: true })).toBeVisible();
  await page.getByLabel('Study name', { exact: true }).fill('Shared starting point');
  await page.getByRole('button', { name: 'Save as study', exact: true }).click();
  await expect(page.getByText('Study saved in My Stuff.', { exact: true })).toBeVisible();
  const aid = (await page.request.get('/api/v2/library').then(r => r.json())).find((a: {title: string}) => a.title === 'Shared starting point').id;
  const other = await page.request.post(`/api/v2/library/${aid}/open`).then(r => r.json());
  const b = other.branches[0];
  b.working_draft.entities[0].root = 'Eb';
  const updated = await page.request.put(`/api/v2/sessions/${other.id}/branches/${b.id}/workspace`, { data: { expected_version: 1, workspace: b.working_draft } }).then(r => r.json());
  expect((await page.request.post(`/api/v2/sessions/${other.id}/branches/${b.id}/workspace/save`, { data: { expected_version: updated.working_draft.version, title: 'Shared starting point' } })).ok()).toBe(true);
  await page.getByLabel('Both roots', { exact: true }).selectOption('D');
  await expect(page.getByText('Draft autosaved', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Save version', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('newer saved version');
  await expect(page.getByRole('heading', { name: 'D major vs D minor' })).toBeVisible();
  await page.getByLabel('Study name', { exact: true }).fill('My separate D study');
  await page.getByRole('button', { name: 'Save as a new study', exact: true }).click();
  await expect(page.getByText('Saved as a new study in My Stuff.', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'My Stuff', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Open My separate D study', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Open Shared starting point', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Eb major vs G minor' })).toBeVisible();
});

test('A failed first save retains the named draft and can be retried', async ({ page }) => {
  await page.goto('/v2');
  await page.getByRole('button', { name: 'Explore major vs minor' }).click();
  await expect(page.getByText('Draft autosaved', { exact: true })).toBeVisible();
  await page.getByLabel('Study name', { exact: true }).fill('Retry my study');
  await page.route('**/workspace/save', route => route.fulfill({ status: 503, contentType: 'text/plain', body: 'Unavailable' }));
  await page.getByRole('button', { name: 'Save as study', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Your draft is still here');
  await expect(page.getByLabel('Study name', { exact: true })).toHaveValue('Retry my study');
  await expect(page.getByRole('heading', { name: 'G major vs G minor' })).toBeVisible();
  await page.unroute('**/workspace/save');
  await page.getByRole('button', { name: 'Save as study', exact: true }).click();
  await expect(page.getByText('Study saved in My Stuff.', { exact: true })).toBeVisible();
});
