import { expect, test } from '@playwright/test';

test('derive, edit, reanalyze, transpose and reopen an exact progression without Tutor calls', async ({ page }) => {
  let turns = 0;
  page.on('request', r => { if (r.url().endsWith('/tutor/turns')) turns++; });
  await page.goto('/v2');
  await page.getByRole('button', { name:'Explore I–V–vi–IV', exact:true }).click();
  await expect(page.getByText('Draft autosaved', { exact:true })).toBeVisible();
  const sid = (await page.getByTestId('v2-active-session').innerText()).replace('Session ', '');
  const bid = (await page.getByTestId('v2-active-branch').innerText()).replace('Branch ', '');
  const draft = () => page.request.get(`/api/v2/sessions/${sid}`).then(r => r.json()).then(s => s.branches.find((b: {id:string}) => b.id === bid).working_draft);
  await page.getByLabel('Progression key', { exact:true }).selectOption('A');
  await expect(page.getByText('Draft autosaved', { exact:true })).toBeVisible();
  await expect(page.getByRole('button', { name:'Select chord 3: F# minor', exact:true })).toBeVisible();
  expect((await draft()).entities.map((e: {kind:string}) => e.kind)).toEqual(['key']);
  await page.getByRole('button', { name:'Select chord 2: E major', exact:true }).click();
  await page.getByLabel('Selected chord root', { exact:true }).selectOption('A');
  await expect(page.getByText('Concrete music · key changes only reanalyze', { exact:true })).toBeVisible();
  await expect(page.getByRole('button', { name:'Select chord 2: A major', exact:true })).toHaveAttribute('aria-pressed','false');
  await page.getByRole('button', { name:'Select chord 2: A major', exact:true }).click();
  await expect(page.getByText('Draft autosaved', { exact:true })).toBeVisible();
  const initial = await draft();
  await page.getByText('Edit this occurrence’s frets', { exact:true }).click();
  await page.getByLabel('Selected voicing string 1', { exact:true }).selectOption('5');
  await expect(page.getByText('Draft autosaved', { exact:true })).toBeVisible();
  const concrete = await draft();
  const firstVoicing = initial.entities.find((e: {kind:string}) => e.kind === 'progression').steps[0].voicing_id;
  expect(concrete.entities.find((e: {id:string}) => e.id === firstVoicing)).toEqual(initial.entities.find((e: {id:string}) => e.id === firstVoicing));
  await page.getByLabel('Progression key', { exact:true }).selectOption('G');
  await expect(page.getByText('Draft autosaved', { exact:true })).toBeVisible();
  const recontext = await draft();
  expect(recontext.entities.filter((e: {kind:string}) => e.kind !== 'key')).toEqual(concrete.entities.filter((e: {kind:string}) => e.kind !== 'key'));
  await page.getByLabel('Transpose distance', { exact:true }).selectOption('2');
  await page.getByRole('button', { name:'Transpose progression', exact:true }).click();
  await expect(page.getByRole('button', { name:'Select chord 3: G# minor', exact:true })).toBeVisible();
  await expect(page.getByText('Draft autosaved', { exact:true })).toBeVisible();
  const shifted = await draft();
  await page.getByRole('button', { name:'Hear progression', exact:true }).click();
  await expect(page.getByRole('button', { name:'Stop playback', exact:true })).toBeVisible();
  await page.getByRole('button', { name:'Stop playback', exact:true }).click();
  await page.getByRole('button', { name:'Select chord 2: B major', exact:true }).click();
  await page.getByRole('button', { name:'Hear selected transition', exact:true }).click();
  await page.getByRole('button', { name:'Stop playback', exact:true }).click();
  await page.getByLabel('Transpose distance', { exact:true }).selectOption('-12');
  await page.getByRole('button', { name:'Transpose progression', exact:true }).click();
  await expect(page.getByRole('alert')).toContainText('unchanged');
  expect(await draft()).toEqual(shifted);
  await page.getByRole('region', {name:'Progression', exact:true}).getByRole('button', { name: 'Select Progression', exact: true }).click();
  await page.getByRole('region', { name: 'Music context', exact: true }).getByLabel('Labels').selectOption('intervals');
  await expect(page.getByText('Draft autosaved', { exact:true })).toBeVisible();
  await page.getByLabel('Study name', { exact:true }).fill('My authored progression');
  await page.getByRole('button', { name:'Save as study', exact:true }).click();
  await expect(page.getByText('Study saved in My Stuff.', { exact:true })).toBeVisible();
  await page.screenshot({ path:'/private/tmp/issue65-desktop.png', fullPage:true });
  const saved = await draft();
  await page.reload();
  await page.locator(`[data-session-id="${sid}"]`).click();
  await page.getByRole('tab', { name:'My authored progression', exact:true }).click();
  expect(await draft()).toEqual(saved);
  await page.getByRole('button', {name:'My Stuff', exact:true}).click();
  await page.getByRole('button', {name:'Open My authored progression', exact:true}).click();
  await expect(page.getByRole('button', {name:'Select chord 3: G# minor', exact:true})).toBeVisible();
  await page.getByRole('region', {name:'Progression', exact:true}).getByRole('button', { name: 'Select Progression', exact: true }).click();
  await expect(page.getByRole('region', { name: 'Music context', exact: true }).getByLabel('Labels')).toHaveValue('intervals');
  const newSid = (await page.getByTestId('v2-active-session').innerText()).replace('Session ', '');
  const newBid = (await page.getByTestId('v2-active-branch').innerText()).replace('Branch ', '');
  const reopened = await page.request.get(`/api/v2/sessions/${newSid}`).then(r => r.json()).then(s => s.branches.find((b:{id:string}) => b.id === newBid).working_draft);
  expect(reopened).toEqual({...saved, version:1});
  await page.setViewportSize({width:320,height:800});
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path:'/private/tmp/issue65-mobile.png', fullPage:true });
  expect(turns).toBe(0);
});
