import { expect, test } from '@playwright/test';
import { installYouTubeFake } from './youtube-fake';

test('queues only the latest seek, follows actual paused time, and cleans up without recreating on callbacks', async ({ page }) => {
  const fake = await installYouTubeFake(page, { autoReady: false });
  const pageErrors: string[] = [];
  page.on('pageerror', error => pageErrors.push(error.message));
  await page.clock.install();
  await page.setViewportSize({ width: 320, height: 900 });
  await page.goto('/e2e/youtube-player.html');
  await expect.poll(() => page.evaluate(() => window.youtubeFake?.players.length)).toBe(1);
  await expect(page.getByTestId('ready')).toHaveText('false');
  await page.getByRole('button', { name: 'Seek earlier' }).click();
  await page.getByRole('button', { name: 'Seek selection' }).click();
  await page.getByRole('button', { name: 'Play selection' }).click();
  await page.evaluate(() => window.youtubeFake.active.ready());
  await expect(page.getByTestId('ready')).toHaveText('true');
  await expect(page.getByTestId('time')).toHaveText('12.5');
  expect(await page.evaluate(() => window.youtubeFake.active.state)).toBe(2);
  await page.evaluate(() => { window.youtubeFake.active.time = 34.25; });
  await expect(page.getByTestId('time')).toHaveText('34.25');
  await page.evaluate(() => window.youtubeFake.active.emitState(3));
  await expect(page.getByTestId('state')).toHaveText('buffering');
  await page.clock.fastForward(1000);
  await expect(page.getByTestId('time')).toHaveText('34.25');
  expect(await page.evaluate(() => window.youtubeFake.players.length)).toBe(1);
  const iframe = page.getByTitle('YouTube video player', { exact: true });
  await expect(iframe).toHaveAttribute('referrerpolicy', 'strict-origin-when-cross-origin');
  await expect(iframe).toHaveAttribute('src', /enablejsapi=1/);
  await expect(iframe).toHaveAttribute('src', /origin=http%3A%2F%2Flocalhost/);
  const box = await iframe.boundingBox();
  expect(box!.width).toBeGreaterThanOrEqual(200);
  expect(box!.height).toBeGreaterThanOrEqual(200);
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(320);
  await page.getByRole('button', { name: 'Play selection' }).click();
  await expect(page.getByTestId('state')).toHaveText('playing');
  await page.evaluate(() => {
    const frame = document.querySelector('iframe')!.getBoundingClientRect();
    window.scrollTo(0, window.scrollY + frame.top + frame.height * 0.75);
  });
  await expect(page.getByTestId('state')).toHaveText('paused');
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.getByRole('button', { name: 'Play selection' }).click();
  await expect(page.getByTestId('state')).toHaveText('playing');
  await page.evaluate(() => {
    Object.defineProperty(document, 'hidden', { value: true, configurable: true });
    document.dispatchEvent(new Event('visibilitychange'));
  });
  await expect(page.getByTestId('state')).toHaveText('paused');
  await page.evaluate(() => { Reflect.deleteProperty(document, 'hidden'); });
  await page.getByRole('button', { name: 'Toggle player' }).click();
  await expect(page.getByTestId('ready')).toHaveText('false');
  expect(await page.evaluate(() => window.youtubeFake.active.destroyed)).toBe(true);
  const reads = await page.evaluate(() => window.youtubeFake.active.reads);
  await page.clock.fastForward(1000);
  expect(await page.evaluate(() => window.youtubeFake.active.reads)).toBe(reads);
  await page.evaluate(() => { window.youtubeFake.active.ready(); window.youtubeFake.active.emitState(1); });
  await expect(page.getByTestId('ready')).toHaveText('false');
  await page.getByRole('button', { name: 'Toggle player' }).click();
  await expect.poll(() => page.evaluate(() => window.youtubeFake.players.filter(player => !player.destroyed).length)).toBe(1);
  expect(fake.scriptRequests()).toBe(1);
  expect(pageErrors).toEqual([]);
});

test('recovers from script failure and reports blocked playback and embedding errors', async ({ page }) => {
  const fake = await installYouTubeFake(page, { failLoads: 1 });
  await page.goto('/e2e/youtube-player.html');
  await expect(page.getByTestId('state')).toHaveText('error');
  await page.getByRole('button', { name: 'Retry video' }).click();
  await expect(page.getByTestId('ready')).toHaveText('true');
  expect(fake.scriptRequests()).toBe(2);
  await page.evaluate(() => window.youtubeFake.active.block());
  await expect(page.getByTestId('state')).toHaveText('blocked');
  await expect(page.getByText('Press Play in the video to start playback.')).toBeVisible();
  await page.getByTitle('YouTube video player', { exact: true }).scrollIntoViewIfNeeded();
  await page.evaluate(() => window.youtubeFake.active.emitState(1));
  await expect(page.getByTestId('state')).toHaveText('playing');
  await expect(page.getByText('Press Play in the video to start playback.')).toHaveCount(0);
  await page.evaluate(() => window.youtubeFake.active.fail(153));
  await expect(page.getByTestId('ready')).toHaveText('false');
  await expect(page.getByRole('alert')).toContainText('identify this site');
  await page.getByRole('button', { name: 'Retry video' }).click();
  await expect(page.getByTestId('ready')).toHaveText('true');
  await page.evaluate(() => window.youtubeFake.active.fail(101));
  await expect(page.getByRole('alert')).toContainText('embedding');
});

test('times out missing readiness, ignores late callbacks, and resets queued seeks on video replacement', async ({ page }) => {
  await installYouTubeFake(page, { autoReady: false });
  await page.clock.install();
  await page.goto('/e2e/youtube-player.html');
  await expect.poll(() => page.evaluate(() => window.youtubeFake?.players.length)).toBe(1);
  await page.getByRole('button', { name: 'Seek selection' }).click();
  await page.clock.fastForward(16000);
  await expect(page.getByTestId('state')).toHaveText('error');
  await page.getByRole('button', { name: 'Retry video' }).click();
  await expect.poll(() => page.evaluate(() => window.youtubeFake.players.length)).toBe(2);
  await page.evaluate(() => window.youtubeFake.players[0].ready());
  await expect(page.getByTestId('ready')).toHaveText('false');
  await page.getByRole('button', { name: 'Replace video' }).click();
  await expect.poll(() => page.evaluate(() => window.youtubeFake.players.length)).toBe(3);
  await page.evaluate(() => window.youtubeFake.active.ready());
  await expect(page.getByTestId('ready')).toHaveText('true');
  await expect(page.getByTestId('time')).toHaveText('0');
  expect(await page.evaluate(() => window.youtubeFake.players.slice(0, -1).every(player => player.destroyed))).toBe(true);
});
